version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:2025.03
    steps:
      - checkout
      - setup_remote_docker
      
      # Login to DockerHub
      - run:
          name: Docker Hub Login
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      
      # Build and push frontend image
      - run:
          name: Build Frontend Image
          command: docker build -t $DOCKERHUB_USERNAME/frontend:latest ./frontend
      - run:
          name: Push Frontend Image
          command: docker push $DOCKERHUB_USERNAME/frontend:latest
      
      # Build and push backend image
      - run:
          name: Build Backend Image
          command: docker build -t $DOCKERHUB_USERNAME/backend:latest ./backend
      - run:
          name: Push Backend Image
          command: docker push $DOCKERHUB_USERNAME/backend:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push:
          context: dockerhub 