version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/docker:24.0
    steps:
      - checkout
      - setup_remote_docker
      
      # Login to DockerHub
      - run:
          name: Docker Hub Login
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      
      # Build and push frontend image
      - run:
          name: Build Frontend Image
          command: docker build -t $DOCKERHUB_USERNAME/frontend:$CIRCLE_SHA1 ./frontend
      - run:
          name: Push Frontend Image
          command: docker push $DOCKERHUB_USERNAME/frontend:$CIRCLE_SHA1
      
      # Build and push backend image
      - run:
          name: Build Backend Image
          command: docker build -t $DOCKERHUB_USERNAME/backend:$CIRCLE_SHA1 ./backend
      - run:
          name: Push Backend Image
          command: docker push $DOCKERHUB_USERNAME/backend:$CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push:
          context: dockerhub 